/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 02 18:20:59 GMT 2025
 */

package prime;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import prime.PrimeNumberFinder;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PrimeNumberFinder_ESTest extends PrimeNumberFinder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Integer integer0 = new Integer(0);
      List<Integer> list0 = List.of(integer0);
      int int0 = PrimeNumberFinder.computeSumOfPrimes(list0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Integer integer0 = new Integer((-2479));
      linkedList0.add(integer0);
      int int0 = PrimeNumberFinder.computeSumOfPrimes(linkedList0);
      assertEquals((-2479), int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      // Undeclared exception!
      PrimeNumberFinder.findPrimes(247, 6609);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      // Undeclared exception!
      try { 
        PrimeNumberFinder.computeSumOfPrimes((List<Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("prime.PrimeNumberFinder", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      List<Integer> list0 = PrimeNumberFinder.findPrimes((-1849), (-1849));
      // Undeclared exception!
      try { 
        PrimeNumberFinder.computeSumOfPrimes(list0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      boolean boolean0 = PrimeNumberFinder.isPrime(289);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      boolean boolean0 = PrimeNumberFinder.isPrime(1963);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      boolean boolean0 = PrimeNumberFinder.isPrime(355);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      boolean boolean0 = PrimeNumberFinder.isPrime(241);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      boolean boolean0 = PrimeNumberFinder.isPrime(2937);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      boolean boolean0 = PrimeNumberFinder.isPrime(2400);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      boolean boolean0 = PrimeNumberFinder.isPrime(2);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      boolean boolean0 = PrimeNumberFinder.isPrime(5);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      boolean boolean0 = PrimeNumberFinder.isPrime(7);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      boolean boolean0 = PrimeNumberFinder.isPrime(3);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      List<Integer> list0 = PrimeNumberFinder.findPrimes(2, 2);
      assertTrue(list0.contains(2));
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      boolean boolean0 = PrimeNumberFinder.isPrime(1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Integer integer0 = new Integer(1294);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      int int0 = PrimeNumberFinder.computeSumOfPrimes(list0);
      assertEquals(11646, int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      List<Integer> list0 = List.of();
      // Undeclared exception!
      try { 
        PrimeNumberFinder.computeSumOfPrimes(list0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PrimeNumberFinder primeNumberFinder0 = new PrimeNumberFinder();
  }
}
